### ISSUE TITLE
Does not work with podcasts (TypeError: 'NoneType' object isn't iterable)

### ISSUE THREAD

**Issue by ylihemmo** [vergoh/micropython-spotify-status-display#1]
Example of what podcast returns from API:
{'json': {'item': None, 'actions': {'disallows': {'resuming': True}}, 'context': None, 'timestamp': 1678973668576, 'progress_ms': 6149773, 'currently_playing_type': 'episode', 'is_playing': True}, 'text': 'No reply content', 'status_code': 200}

Script ends up in state where None ends up to be iterated and it fails:
TypeError: 'NoneType' object isn't iterable

Quick fix that prevents this and prints 'Podcast' to screen (no podcast or episode name apparently available at the moment from API).

diff from spotify.py:

```
252a253,255
>         if r['json']['currently_playing_type'] == 'episode':
>             r['json']['item'] = {'podcast': 'true'}
>
343,344c346,351
<             self.oled.show(cp['item'].get('artists', [{}])[0].get('name'), cp['item'].get('name'))
<             await asyncio.sleep(seconds)
---
>             if 'podcast' in cp['item']:
>                 self.oled.show('Podcast', '')
>                 await asyncio.sleep(seconds)
>             else:
>                 self.oled.show(cp['item'].get('artists', [{}])[0].get('name'), cp['item'].get('name'))
>                 await asyncio.sleep(seconds)
```

**Comment by vergoh** [comment]
`currently_playing_type` already exists in the response as a communication of the playback type, so instead of modifying the response, it would be better to refactor the implementation to use that field as according to the api documentation (https://developer.spotify.com/documentation/web-api/reference/#/operations/get-the-users-currently-playing-track) it can have any of the following values:
- track
- episode
- ad
- unknown

Stumbled also to https://developer.spotify.com/community/news/2020/03/20/introducing-podcasts-api/ which points out there's a new type parameter for the query which defaults to `track` only and that's why the episode details aren't visible. As a result, instead of using just the `https://api.spotify.com/v1/me/player/currently-playing` endpoint, using `https://api.spotify.com/v1/me/player/currently-playing?additional_types=track,episode` provides the missing details. However, the structure isn't the same for `track` and `episode` so some modifications will still be needed.
