### ISSUE TITLE
RuntimeError: Error 202 - when pressing either of buttons.

### ISSUE THREAD

**Issue by ylihemmo** [vergoh/micropython-spotify-status-display#2]
Screen says:
Spotify status
next api error
202

Using:
MicroPython v1.19.1 on 2022-06-18; ESP32 module with ESP32

```
next button pressed
POST https://api.spotify.com/v1/me/player/next
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "spotify.py", line 511, in start
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "spotify.py", line 484, in _looper
  File "spotify.py", line 168, in _handle_buttons
  File "spotify.py", line 308, in _next_playback
  File "spotify.py", line 187, in _validate_api_reply
RuntimeError: Error 202 - 
```

Might be user error, but this was working ok earlier.

**Comment by vergoh** [comment]
The implementation has been written to support those Spotify API reply status codes that Spotify's own API documentation describes. Everything else results in an error since the behaviour is unspecified by Spotify. For the player/next the documentation is in https://developer.spotify.com/documentation/web-api/reference/skip-users-playback-to-next-track which still shows the possible responses as 204, 401, 403 and 429. For some reason, you got a 202 reply even when the documentation doesn't describe such possibility.

I'll have to check if I can get this issue reproduced and if the same happens also with other API calls. One possible solution could be to add "202" as some sort of "ok enough" status code for all APIs currently supporting 204 (= "no content").

**Comment by vergoh** [comment]
Can't reproduce, the response I'm getting is 204 every time. However, that doesn't still mean the problem doesn't exist. https://community.spotify.com/t5/Spotify-for-Developers/Transfer-playback-API-returns-202-instead-of-204/td-p/5517850 suggests the API documentation may not be 100% accurate or up to date. I'll add 202 as a supported reply for those cases where the reply content itself doesn't matter, which should solve the issue of an error getting reported in the cases when the Spotify API doesn't behave exactly as documented.

**Comment by ylihemmo** [comment]
Thanks, fixed the issue. For some reason API response for all of these is 202.
next status received: 202
pause status received: 202
resume status received: 202
