### ISSUE TITLE
OSError: [Errno 113] ECONNABORTED

### ISSUE THREAD

**Issue by renatojobal** [vergoh/micropython-spotify-status-display#4]
I am facing this error:
```
MPY: soft reboot
no "memdebug" file or directory found, memory debug output disabled
buttons enabled
network configured
connected at 192..... as spostatus
listening on ('0.0.0.0', 80) as http://192.... - login at http://spostatus.local
client connected from ('192....', 57234)
GET / HTTP/1.1
not callback path, giving login
client connected from ('192....', 57235)
GET /callback/?code=A... HTTP/1.1
got params: {'code': 'A...'}
reply reports error: None
authorization_code content: A....()
POST https://accounts.spotify.com/api/token
OSError: [Errno 113] ECONNABORTED
failed, retrying...
POST https://accounts.spotify.com/api/token
OSError: -202
token status received: 0
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "spotify.py", line 561, in start
  File "asyncio/core.py", line 1, in run_until_complete
  File "asyncio/core.py", line 1, in run_until_complete
  File "asyncio/core.py", line 1, in run_until_complete
  File "spotify.py", line 507, in _looper
  File "spotify.py", line 375, in _initial_token_request
  File "spotify.py", line 234, in _get_api_tokens
  File "spotify.py", line 224, in _validate_api_reply
RuntimeError: token api error 0 - -202
MicroPython v1.21.0 on 2023-10-05; Generic ESP32 module with ESP32
Type "help()" for more information.
```
This happens after I go to the prompted url and accept the permissions.

Btw, I am not using an oled screen, I just commented all the oled part for now. Maybe this could be something?

My Esp32 is this: ESP-WROOM-32 TYPE C (CP2104)
Using Mycropython to load the files
Thony: 4.1.4
Python: 3.10.11

I just have the two buttons connected

Thank you in advance for your reply!

**Comment by vergoh** [comment]
https://github.com/vergoh/micropython-spotify-status-display/blob/master/src/spotify.py#L224 is an empty line so you have likely also either added or removed some lines which in turn makes tracking the actual error location harder.

Did you try the login multiple times? Does this same happen every time?

There's always the possibility that something in the Spotify login / api token procedure has changed since the time I wrote the implementation. Once you get the token, there doesn't appear to be anything restricting it to be renewed so I haven't tested this part of the implementation in most likely over half year. If the situation repeats, I can obviously test it out to see if there's indeed some new issue.

The idea of using the implementation with only the buttons but without the oled display is also valid. Probably is wouldn't require too much refactoring to make also the oled configurable as optional and in that case polling the status wouldn't be needed most of the time.

**Comment by renatojobal** [comment]
I think it had something to do with the board. I changed the pins as you pointed out in the issue https://github.com/vergoh/micropython-spotify-status-display/issues/3 and now everything works like a charm. Thank you very much!!!

To make the code work with only the button, I just commented out the lines with `self.oled` and added `pass` to the empty `if`` statements. (For that reason the errors appear to be on an empty line, but in reality it was here):
![image](https://github.com/vergoh/micropython-spotify-status-display/assets/35740463/2736b5bf-32ba-4eae-afdd-5251c86cd4d3) 

I will now attempt to make the OLED screen (SSD1315) work and provide additional comments on that other issue.
